# test config bs11.16 page, waveform, 11 conditions, no looping


testname: NES
testId: nes
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
language: ja


pages:

    - type: NES
      id: var_5_active_sigma_500
      name: test
      content: "二つの音声A,Bを聞いてその自然さを評価してください．<br>
                自然さに差がある場合は評価に差をつけてください．<br>
                問題は全28問です．<br>
                最初の3問は練習用の問題です．"

      enableLooping: true 
      createAnchor35: false
      createAnchor70: false
      dummy: exp/test1/dummy
      dummy_len: 3
      stimuli: exp/test1/var_5_active_sigma_500/wav
      stimuli_num: 500
      perturbation_num: 5
      test_len: 25


    - type: finish
      name: お疲れさまでした
      content: 結果をコピーして回答してください
      showResults: true
      writeResults: true
